import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "./component/menu";
import Footer from "./component/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Portfolio",
  description: "Generated by Aravinthan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col md:flex-row">
          <Menu />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
